### PR TITLE
Feat/abebe

### PR DESCRIPTION
**Pull request by f947**
Got some implementation of Login And Authorization model and repository classes.

### CODE REVIEW

**Comment by f947** [comment]
Sounds good great to me.

Thank you!

**Comment by calebTree** [comment]
Your commits are behind main. That is the reason for merge conflicts.

**Comment by dnguyen000** [comment]
@calebTree theres something setup weird in @f947's local machine. On initial setup the binary files are always generated and previous work was committed to the main branch. I worked with him to get his quiz controller cleanup in the other PR and suggested the same thing to checkout a new feature branch from main for the user login changes. We can close this PR as it won't be merged in.

**Comment by calebTree** [comment]
> @calebTree theres something setup weird in @f947's local machine. On initial setup the binary files are always generated and previous work was committed to the main branch. I worked with him to get his quiz controller cleanup in the other PR and suggested the same thing to checkout a new feature branch from main for the user login changes. We can close this PR as it won't be merged in.

Cool that's what I would do.

**Pull request closed without merging**
