### PR TITLE
feat/st-49

### PR DESCRIPTION
**Pull request by calebTree**
- Compound, and quizzes associated with `userId`.

### CODE REVIEW

**Comment by dnguyen000** [comment]
@calebTree I'm confused by the number of changes going into this PR. I understand there is overlap between work here, but what changes are you introducing from your side?  For example, there is a change to `CompoundDTO.java` but in comparison to what is in the main branch, there is actually no change. In addition, there appears to be changes from #39 but it's not fully together. If this gets merged in first, there's going to be a lot of conflict in #39 and vice versa.

**Comment by calebTree** [comment]
You're right, I started using an IntelliJ command to cleanup code and it is removing white-space.

- To only color words
  - `git diff main --color-words src/main/java/edu/metrostate/ics499/team2/model/CompoundDTO.java`
- To diff and ignore white-space
  - `git diff -w main src/main/java/edu/metrostate/ics499/team2/model/CompoundDTO.java`

I also noticed I missed a commit where apparently we did overlap allot. I'll look closer at that commit and try to get everything we need in.
Screen Shot 2022-04-26 at 10 52 16 AM

**Comment by calebTree** [comment]
I'm pretty sure this commit e1d3ca3 has everything.

**Review by dnguyen000 — CHANGES_REQUESTED** [review]
@calebTree Functionally this looks good; minor differences with #39 reside with stylistic programming differences. One minor change/update is [here](https://github.com/dnguyen000/ICS-499/blob/main/pom.xml#L126-L127), we should update this to align with [Java 11](https://github.com/dnguyen000/ICS-499/blob/main/pom.xml#L17)

**Review by dnguyen000 — APPROVED** [review]
Nvm, just saw the previous comment. We can address that in the next PR.

**Review by atvick21 — APPROVED** [review]

**Review by f947 — APPROVED** [review]

**Comment by calebTree** [comment]
> @calebTree Functionally this looks good; minor differences with #39 reside with stylistic programming differences. One minor change/update is [here](https://github.com/dnguyen000/ICS-499/blob/main/pom.xml#L126-L127), we should update this to align with [Java 11](https://github.com/dnguyen000/ICS-499/blob/main/pom.xml#L17)

I explicitly set Java 16 back on commit 6535ae5 because I was following IntelliJ code inspection regarding `collect(Collectors.toList())` can be replaced by just `toList()`.

image
 I learned Java 16 was first to allow that. 

https://stackoverflow.com/questions/65969919/differences-of-java-16s-stream-tolist-and-stream-collectcollectors-tolist 

At some point that change was reverted again apparently.

**Comment by dnguyen000** [comment]
@calebTree We can update it back to java 16.

**Review by wale0 — APPROVED** [review]

**Pull request merged**
