### PR TITLE
Added changes for Flashcard class and Game Abstract class

### PR DESCRIPTION
**Pull request by dnguyen000**

### CODE REVIEW

**Review by calebTree — COMMENTED** [review]
I found none of the `@GetMapptings` are working such as: `/flashcards`, `/all`, `/answers`, and `/add`.

**Review by calebTree — APPROVED** [review]
I updated `.gitignore` to defaults (I found) and included JUnit in pom.xml.

**Review by wale0 — APPROVED** [review]
nice work!

**Review by atvick21 — APPROVED** [review]
I would say to push even if Caleb found something not working just to have the project  created and we can fix after

**Review by f947 — APPROVED** [review]
As Caleb tested that works okay . just push to the main branch.

**Pull request merged**
