### PR TITLE
JWT

### PR DESCRIPTION
**Pull request by calebTree**
JWT authentication seems to be working.

- Notice a few comments I hope are helpful.
- A few modifications from the freeCodeCamp guide were necessary.
  -  Getting Postman to work with POST and CSRF security. [guide](https://dev.to/shane/using-postman-with-java-spring-and-csrf-tokens-di0)
  - Casting `UserDetails` to our `RegisteredUser` model. [guide](https://www.baeldung.com/spring-security-authentication-with-a-database)
- A few design decisions on the DTO pattern. [guide](https://www.baeldung.com/java-dto-pattern)
  - The password is not returned when listing users.
  - Only password and username are sent when logging in.<br><br>
- [x] _Roles_ have not been implemented.
- [ ] _Logout_ has not been implemented.
- [ ] Compare the instructors JWT code to see if improvements can be made.

### CODE REVIEW

**Review by f947 — APPROVED** [review]
for me it looks good, i was reading different sources and were start coding. it's basically preety much the same concept.

we can also add this method to return false and override if we wish to add to check the account is not locked.

private boolean isLocked = false;
public boolean isAccountNonLocked() {
	        return !isLocked;
	    }

**Review by dnguyen000 — APPROVED** [review]
Great job @calebTree!

**Comment by calebTree** [comment]
Thanks @dnguyen000, I appreciate that. The mapping in the controller was temporarily removed in this last commit because I was following a guide that was just really simplifying everything. When we need a DTO or DAO we can go back to the previous pattern.  Here is [the guide](https://www.getarrays.io/courses/1463430/lectures/33546927) I was starting to follow.

**Review by wale0 — APPROVED** [review]

**Comment by calebTree** [comment]
I brought back the `DTO` and renamed it `DAO` in my last commit to be more accurate.

**Pull request merged**
